title: 'Site Settings'
data:
  site_name: Whisp
  full_logo: branding/whisp-logo-with-text.png
  favicon: branding/logo.png
  footer_text: 'The pure PHP SSH server built specifically for TUIs'
  github_url: 'https://github.com/whispphp/whisp'
